// ======================== Action Types

// Global Error - SETTER, REMOVER
export const GLOBAL_ERROR_SET = "GLOBAL_ERROR_SET";
export const GLOBAL_ERROR_REMOVE = "GLOBAL_ERROR_REMOVE";

// Global Success - SETTER, REMOVER
export const GLOBAL_SUCCESS_SET = "GLOBAL_SUCCESS_SET";
export const GLOBAL_SUCCESS_REMOVE = "GLOBAL_SUCCESS_REMOVE";

// All Pokemons - SETTER
export const ALL_POKEMONS_GET = "GET_ALL_POKEMONS";

// Pokemons - FILTER (2), ORDER, REMOVER, SETTER BY NAME
export const POKEMONS_FILTER_BY_TYPE = "POKEMONS_FILTER_BY_TYPE";
export const POKEMONS_FILTER_BY_SOURCE = "POKEMONS_FILTER_BY_SOURCE";
export const POKEMONS_ORDER = "POKEMONS_ORDER";
export const POKEMONS_REMOVE = "POKEMONS_REMOVE";
export const POKEMONS_BY_NAME_GET = "POKEMONS_GET_BY_NAME";

// Pokemon Detail - SETTER, REMOVER
export const POKEMON_DETAIL_GET = "POKEMON_DETAIL_GET";
export const POKEMON_DETAIL_REMOVE = "POKEMON_DETAIL_REMOVE";

// Types - SETTER
export const TYPES_GET = "TYPES_GET";

// Create Pokemon
export const CREATE_POKEMON = "CREATE_POKEMON";